Tca 41/error page
0xJamin/techconfsafrica pull request #4
Opened 2023-07-26 09:28 UTC by CodeLeom

Please review sir @0xJamin

2023-07-26 23:36 UTC, 0xJamin requested changes
@CodeLeom  some changes to update here Boss

2023-07-26 23:36 UTC, 0xJamin commented on app/not-found.tsx
> +      <div className="w-screen h-screen flex justify-center items-center">
use `container` here

2023-07-26 23:36 UTC, 0xJamin commented on app/not-found.tsx
> +    <div>
This should be a `section`

2023-07-26 23:36 UTC, 0xJamin commented on app/not-found.tsx
> +            <h1 className="text-6xl font-bold text-red-600">Oops</h1>
Update heading to match design

2023-07-26 23:36 UTC, 0xJamin commented on app/not-found.tsx
> +            <p className="text-4xl font-semi-bold text-gray-500">
update font size

2023-07-26 23:36 UTC, 0xJamin commented on app/not-found.tsx
> +              <button className="bg-black text-white font-bold py-5 px-10 rounded inline-flex tracking-wider mr-8">
Buttons should be reusable components, and should fit design

2023-07-26 23:36 UTC, 0xJamin commented on app/not-found.tsx
> +          <Image
Image size should match design

2023-12-17 11:53 UTC, 0xJamin requested changes
@CodeLeom  I'm creating a migration from Nextjs to [Astro](https://astro.build/),

So unfortunately you'd have to rework on this PR again after pulling the changes from the `develop` branch (please hold on the migration is not done yet)

We'll still be using `react` components where necessary, but astro is by default out choice

2023-12-17 11:55 UTC, 0xJamin commented
You can move your files to the `old` folder and when you've replicated the changes in Astro, we can then delete it

2023-12-20 12:35 UTC, 0xJamin commented
@CodeLeom  Please convert this component to an Astro component.
Thanks

2023-12-26 16:18 UTC, closed without merging

2023-12-26 16:18 UTC, CodeLeom commented
made a new pr